### ISSUE TITLE
Wallpaper Please.

### ISSUE THREAD

**Issue by ItsTerm1n4l** [mahmoudk1000/awedots#1]
Please could you link the wallpaper displayed on your reddit post?

**Comment by mahmoudk1000** [comment]
Here
![wall](https://github.com/mahmoudk1000/awedots/assets/24735185/2eb2faaa-90d3-4a72-98ef-08e1e3537363)

**Comment by ItsTerm1n4l** [comment]
Tysm! awesome rice BTW!
